export const FORECAST_DATA_REQUEST = "FORECAST_DATA_REQUEST";
export const FORECAST_DATA_SUCCESS = "FORECAST_DATA_SUCCESS";
export const FORECAST_DATA_FAIL = "FORECAST_DATA_FAIL";

export const FORECAST_NOT_SELECTED = "FORECAST_NOT_SELECTED";
export const FORECAST_NOT_SELECTED_UPDATE = "FORECAST_NOT_SELECTED_UPDATE";
